apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-uums
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/rycole-appstudio/integration1-sbeh-tenant/integ-app-mvfc/hacbs-test-project-uums@sha256:c9c77e405fdde982faab9dfc6284e1bac41546b170cb0ad7260dd4a77bcc9228
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
