apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-uums
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-uums
    app.kubernetes.io/part-of: integ-app-mvfc
  name: hacbs-test-project-uums
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-uums
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-uums
    spec:
      containers:
      - image: quay.io/rycole-appstudio/integration1-sbeh-tenant/integ-app-mvfc/hacbs-test-project-uums@sha256:c9c77e405fdde982faab9dfc6284e1bac41546b170cb0ad7260dd4a77bcc9228
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
